config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations, :passwords, :confirmations, :unlocks]
  root to: 'pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :projects, path: 'portfolio', only: %i[index show]
  # resources :programmes, path: 'skills', only: :index

  namespace :admin do
    get "/", to: "dashboards#dashboard", as: :dashboard
    resources :projects, except: %i[index show] do
      resources :project_programmes, path: 'project_skills', only: %i[new create destroy]
    end
    resources :programmes, path: 'skills', except: %i[index show]
  end
end

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <% next if message.blank? %>

  <div class="alert alert--<%= semantic_class_for(type) %>"
       role="alert"
       data-controller="alert"
       data-alert-delay-value="5000">
    <div class="alert__icon">
      <%= inline_svg_tag semantic_icon_for(type), class: "icon" %>
    </div>
    <span class="t-text alert__message"><%= message %></span>
    <%= button_tag type: "button", class: "btn btn--icon btn--tertiary btn--#{semantic_class_for(type)}",
                   data: { action: "click->alert#dismissAlert" }, aria: { label: "Dismiss" } do %>
      <%= inline_svg_tag "icons/close.svg", class: "icon" %>
    <% end %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer__social-links" id="footer">
    <a href="http://www.github.com/kotomyrau" class="fa fa-github" target='blank'></a>
    <a href="https://www.linkedin.com/in/kotomyra-uchida/" class="fab fa-linkedin" target='blank'></a>
    <a href="mailto:kotomairau@gmail.com" class="fas fa-envelope-square"></a>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="nav"  data-nav-target="nav">
  <%= link_to 'Kotomaira Uchida', root_path, class: "nav__title" %>

  <% if user_signed_in? %>
    <ul class="nav__links" data-nav-target="navLinks">
      <li data-nav-target="link"><%= link_to "Download CV", "/koto_uchida_cv_2025.pdf", target: '_blank', class: "link" %></li>
      <% if current_user.role_admin? %>
        <li data-nav-target="link"><%= link_to "Manage", admin_dashboard_path, class: "link" %></li>
      <% end %>
      <li data-nav-target="link"><%= button_to "Log out", destroy_user_session_path, method: :delete, class: "link" %></li>
    </ul>
    <div class="nav__burger" data-action="click->nav#toggle">
      <div class="burger-line burger-line--1 line1"></div>
      <div class="burger-line burger-line--2 line2"></div>
      <div class="burger-line burger-line--3 line3"></div>
    </div>
  <% end %>
</nav>