config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations, :passwords, :confirmations, :unlocks]
  root to: 'pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :projects, path: 'portfolio', only: %i[index show]
  # resources :programmes, path: 'skills', only: :index

  namespace :admin do
    get "/", to: "dashboards#dashboard", as: :dashboard
    resources :projects, except: %i[index show] do
      resources :project_programmes, path: 'project_skills', only: %i[new create destroy]
    end
    resources :programmes, path: 'skills', except: %i[index show]
  end
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :project_programmes, dependent: :destroy
  has_many :programmes, through: :project_programmes
  has_one_attached :project_image
  has_many_attached :project_images

  validates :title, presence: true, uniqueness: true
  validates :description, presence: true
  validates :project_image, presence: true
  # validates :project_date, presence: true
  # validates :link, presence: true
  # validates :category, presence: true
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::BaseController

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to project_path(@project), notice: 'Your project has been created!'
    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
    @project_programme = ProjectProgramme.where(project_id: @project.id)
  end

  def update
    @project = Project.find(params[:id])

    if @project.update(project_params)
      redirect_to project_path(@project), notice: 'Your project was successfully modified'
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    if @project.destroy
      flash[:notice] = "Your project has been deleted"
      redirect_to admin_dashboard_path
    else
      redirect_to project_path(@project), notice: 'There was a problem, this project was not deleted!'
    end
  end

  private

  def project_params
    params.require(:project).permit(:title, :description, :private, :company, :start_date, :end_date, :link, :image_carousel, :project_image, project_images: [])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.order('start_date DESC')
  end

  def show
    @project = Project.find(params[:id])
    @project_image = @project.project_image
    @project_images = @project.project_images
  end
end

app/views/projects/index.html.erb
<main class="main-container" id="portfolio">
  <%= turbo_frame_tag "portfolio" do %>
    <% if @projects.empty? %>
      <header class="page-header">
        <div class="page-header__main">
          <h3 class="page-header__title">I am currently working on projects...</h3>
        </div>
      </header>
    <% else %>
      <header class="page-header">
        <div class="page-header__main">
          <h3 class="page-header__title"><%= current_user.tablecheck? ? "What's on the Menu 🍽️" : "Featured projects" %></h3>
        </div>
      </header>
      <div class="cards-grid" id="projects">
        <% @projects.each do |project| %>
          <%= link_to project_path(project), target: "_top", class: "card" do %>
            <div class="card__thumbnail">
              <% if project.project_image.attached? %>
                <%= cl_image_tag project.project_image.key, overflow: :hidden %>
              <% end %>
            </div>
            <div class="card__content">
              <header class="card__header">
                <h4 class="card__title truncate"><%= project.title %></h4>
                <%= content_tag(:p, truncate(project.description, length: 100), class: "t-caption truncate truncate--two") if project.description.present? %>
              </header>
              <div class="card__skills">
                <% project.programmes.each do |programme| %>
                  <div class="badge"><span><%= programme.name %></span></div>
                <% end if project.programmes.present? %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  <% end %>
</main>

app/views/projects/show.html.erb
<main class="project">
  <header class="project-header">
    <div class="project-header__top">
      <%= link_to "Back to all projects", root_path(anchor: "projects"), data: { turbo: false }, class: "link link--secondary" %>
    </div>
    <% if @project.project_image.attached? %>
      <div class="project-header__image">
        <%= cl_image_tag @project_image.key, overflow: :hidden %>
      </div>
    <% end %>
    <div class="project-header__main">
      <h3 class="project-header__title"><%= @project.title %></h3>
    </div>
  </header>
  <div class="project-content">
    <div class="project-content__details">
      <div class="project-content__description">
        <p><%= @project.description %></p>
      </div>
      <div class="project-content__attributes attributes-list">
        <%= content_tag(:article, class: "attribute") do %>
          <div class="attribute__content attribute__content--horizontal badges badges--sm">
            <% @project.programmes.each do |programme| %>
              <div class="badge"><span><%= programme.name %></span></div>
            <% end %>
          </div>
        <% end if @project.programmes.present? %>
        <%= content_tag(:article, class: "attribute") do %>
          <header class="attribute__header">
            <%= inline_svg_tag "icons/calendar_month.svg", class: "icon attribute__icon" %>
          </header>
          <div class="attribute__content attribute__content--horizontal">
            <span class="t-text"><%= @project.start_date.strftime("%b %Y") %> - <%= @project.end_date.present? ? @project.end_date.strftime("%b %Y") : 'Ongoing' %></span>
          </div>
        <% end if @project.start_date.present? %>
        <%= content_tag(:article, class: "attribute") do %>
          <header class="attribute__header">
            <%= inline_svg_tag "icons/link.svg", class: "icon attribute__icon" %>
          </header>
          <div class="attribute__content attribute__content--horizontal">
            <span class="t-text"><%= link_to website_name(@project.link), @project.link, target: "_blank" %></span>
          </div>
        <% end if @project.link.present? %>
        <%= content_tag(:article, class: "attribute") do %>
          <header class="attribute__header">
            <%= inline_svg_tag "icons/work.svg", class: "icon attribute__icon" %>
          </header>
          <div class="attribute__content attribute__content--horizontal">
            <span class="t-text"><%= @project.company %></span>
          </div>
        <% end if @project.company.present? %>
      </div>
    </div>

    <%= content_tag(:div, class: "project-content__actions") do %>
      <%= link_to "Edit Project", edit_admin_project_path(@project), class: "btn btn--primary" %>
      <%= link_to "Add Skill", new_admin_project_project_programme_path(@project), class: "btn btn--primary" %>
    <% end if current_user.role_admin? %>

    <% unless @project.image_carousel? %>
      <div class="project__images">
        <% if @project_images.any? %>
          <% @project_images.each do |image| %>
            <div class="project__image" style="width:100%">
              <%= cl_image_tag image.key, overflow: :hidden %>
            </div>
          <% end %>
        <% else %>
          <p>No images available for this project.</p>
        <% end %>
      </div>
    <% end %>
  </div>
  <%= link_to "Back to all projects", root_path(anchor: "projects"), data: { turbo: false }, class: "link link--secondary" %>
</main>