config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations, :passwords, :confirmations, :unlocks]
  root to: 'pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :projects, path: 'portfolio', only: %i[index show]
  # resources :programmes, path: 'skills', only: :index

  namespace :admin do
    get "/", to: "dashboards#dashboard", as: :dashboard
    resources :projects, except: %i[index show] do
      resources :project_programmes, path: 'project_skills', only: %i[new create destroy]
    end
    resources :programmes, path: 'skills', except: %i[index show]
  end
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < Admin::BaseController

  def dashboard
    @projects = Project.order('start_date DESC')
  end
end

app/views/admin/dashboards/dashboard.html.erb
<main>
  <header class="page-header">
    <div class="page-header__top">
      <h5>
        Admin Dashboard
      </h5>
      <div class="page-header__actions">
        <%= link_to "Add Skill to Profile", new_admin_programme_path, class: "btn btn--primary" %>

        <%= link_to "Add a new Project", new_admin_project_path, class: "btn btn--primary" %>
        <div class="account-settings">
          <%#= link_to "View My Projects", projects_path  %>
          <%#= link_to "Add a new Skill", new_user_programme_path(@user)%>
        </div>
        <div class="basic-btn">
          <%#= link_to "Edit Account", edit_user_registration_path %>
        </div>

      </div>
    </div>
    <div class="page-header__main">
      <h1 class="page-header__title">Manage your Portfolio</h1>
      <p class="page-header__subtitle">Manage your projects and skills here.</p>
    </div>
  </header>
  <div class="page-content">
    <% @projects.each do |project| %>
      <%= link_to project_path(project), class: "card" do %>
        <%= project.title %>
      <% end %>
    <% end %>
<!--    <div class="basic-btn">-->
      <%#= link_to "Log out", destroy_user_session_path, method: :delete %>
<!--    </div>-->
  </div>
</main>